using System;
namespace PhotoshopFile
{
	public enum ResourceID
	{
		Undefined,
		MacPrintInfo = 1001,
		ResolutionInfo = 1005,
		AlphaChannelNames,
		DisplayInfo,
		Caption,
		BorderInfo,
		BackgroundColor,
		PrintFlags,
		MultichannelHalftoneInfo,
		ColorHalftoneInfo,
		DuotoneHalftoneInfo,
		MultichannelTransferFunctions,
		ColorTransferFunctions,
		DuotoneTransferFunctions,
		DuotoneImageInfo,
		BlackWhiteRange,
		EpsOptions = 1021,
		QuickMaskInfo,
		LayerStateInfo = 1024,
		WorkingPathUnsaved,
		LayersGroupInfo,
		IptcNaa = 1028,
		RawFormatImageMode,
		JpegQuality,
		GridGuidesInfo = 1032,
		ThumbnailBgr,
		CopyrightInfo,
		Url,
		ThumbnailRgb,
		GlobalAngle,
		ColorSamplersObsolete,
		IccProfile,
		Watermark,
		IccUntagged,
		EffectsVisible,
		SpotHalftone,
		DocumentSpecific,
		UnicodeAlphaNames,
		IndexedColorTableCount,
		TransparentIndex,
		GlobalAltitude = 1049,
		Slices,
		WorkflowUrl,
		JumpToXpep,
		AlphaIdentifiers,
		UrlList,
		VersionInfo = 1057,
		ExifData1,
		ExifData3,
		XmpMetadata,
		CaptionDigest,
		PrintScale,
		PixelAspectRatio = 1064,
		LayerComps,
		AlternateDuotoneColors,
		AlternateSpotColors,
		LayerSelectionIDs = 1069,
		HdrToningInfo,
		PrintInfo,
		LayerGroupsEnabled,
		ColorSamplers,
		MeasurementScale,
		TimelineInfo,
		SheetDisclosure,
		FloatDisplayInfo,
		OnionSkins,
		CountInfo = 1080,
		PrintSettingsInfo = 1082,
		PrintStyle,
		MacNSPrintInfo,
		WinDevMode,
		AutoSaveFilePath,
		AutoSaveFormat,
		PathInfo = 2000,
		ClippingPathName = 2999,
		LightroomWorkflow = 8000,
		PrintFlagsInfo = 10000
	}
}
